# Generated by Django 5.2.1 on 2025-06-24 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('freelancer', 'freelancer'), ('client', 'client')], max_length=20)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('200+', '200+ employees')], max_length=20, null=True)),
                ('skills', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
